package com.banking.view;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Md Yasin Arif
 */
public class Authentication extends javax.swing.JFrame {

    public static JFrame login = new Authentication();
    public JFrame myPage;
    public JFrame createAccount;
    
    public Authentication() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        create_acc = new javax.swing.JButton();
        inp_pin = new javax.swing.JPasswordField();
        En_acc_no = new javax.swing.JLabel();
        logIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        i_banking = new javax.swing.JLabel();
        Inp_ent_acc_no = new javax.swing.JTextField();
        pin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3), "Authentication", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 0, 36), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        create_acc.setBackground(new java.awt.Color(204, 204, 204));
        create_acc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        create_acc.setForeground(new java.awt.Color(0, 51, 153));
        create_acc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_add_list_16px.png"))); // NOI18N
        create_acc.setText("Create Account");
        create_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_accActionPerformed(evt);
            }
        });
        jPanel1.add(create_acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 375, -1, -1));

        inp_pin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(inp_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 309, 222, -1));

        En_acc_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        En_acc_no.setForeground(new java.awt.Color(255, 255, 255));
        En_acc_no.setText("Enter  Account No.");
        jPanel1.add(En_acc_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 255, -1, 25));

        logIn.setBackground(new java.awt.Color(204, 204, 204));
        logIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logIn.setForeground(new java.awt.Color(0, 51, 153));
        logIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_login_rounded_right_16px.png"))); // NOI18N
        logIn.setText("LogIn");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        jPanel1.add(logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 375, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_lock_16px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 255, 24, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_key_16px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 316, -1, -1));

        i_banking.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        i_banking.setForeground(new java.awt.Color(255, 255, 255));
        i_banking.setText("iBANKING");
        jPanel1.add(i_banking, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 132, 246, 104));

        Inp_ent_acc_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Inp_ent_acc_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 257, 222, -1));

        pin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pin.setForeground(new java.awt.Color(255, 255, 255));
        pin.setText("PIN");
        jPanel1.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_shutdown_16px.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 376, 89, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Islami Bank Banglades Ltd.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 400, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        // TODO add your handling code here:
              String userid;
              userid = Inp_ent_acc_no.getText();
              String pwd = new String(inp_pin.getPassword());
             if(userid.equals("m") && pwd.equals("1")){
    
             JOptionPane.showMessageDialog(this, "Login Successfull");
             new HomePageView().setVisible(true);
             this.dispose();
    }else{
             JOptionPane.showMessageDialog(this,"Invalid Account No or Pin");
             inp_pin.setText(null);
             }
        
        
    }//GEN-LAST:event_logInActionPerformed

    private void create_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_accActionPerformed
        // TODO add your handling code here:
      login.setVisible(false);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
               //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
               createAccount = new AccountView();
               createAccount.setVisible(true);
            
            
            }
        });
    }//GEN-LAST:event_create_accActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Banking System", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel En_acc_no;
    private javax.swing.JTextField Inp_ent_acc_no;
    private javax.swing.JButton create_acc;
    private javax.swing.JLabel i_banking;
    private javax.swing.JPasswordField inp_pin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logIn;
    private javax.swing.JLabel pin;
    // End of variables declaration//GEN-END:variables
}
